## HANDLING COGNITO DUPE username or EMAIL error (from lambda)
## Eg. [
##   {
##     "message": "User account already exists",
##     "code": "UsernameExistsException",
##     "time": "2021-05-25T00:17:21.555Z",
##     "requestId": "1de84af6-e741-4fc6-a352-38a7d4c531b8",
##     "statusCode": 400,
##     "retryable": false,
##     "retryDelay": 16.38043756088623
##   }
## ]

#if($util.isNull($ctx.result.errors)) 
    ## No errors? we proceed...
    $util.qr($ctx.stash.put('token', $ctx.result.token))
    {}
#else
    ## TODO: more robust error handling (not hard-coded)
  $utils.error(
    $ctx.result.errors[0].message, 
    $ctx.result.errors[0].code, 
    {}, 
    $ctx.result.errors)
#end